### ISSUE TITLE
Build failure in branch xquery3

### ISSUE THREAD

**Issue by lcahlander** [malteseduck/sonar-xquery-plugin#24]
When trying to build using Maven 3.6.0 and Java version 1.8.0_172, I get the following error in the xquery3 branch:

[ERROR] /Users/lcahlander/Downloads/sonar-xquery-plugin-xquery3/target/generated-sources/antlr4/org/sonar/plugins/xquery/parser/XQueryParser.java:[13,35] cannot find symbol
[ERROR]   symbol: class MultiChannelBaseParser
[ERROR] /Users/lcahlander/Downloads/sonar-xquery-plugin-xquery3/target/generated-sources/antlr4/org/sonar/plugins/xquery/parser/XQueryParser.java:[218,9] method does not override or implement a method from a supertype
[ERROR] /Users/lcahlander/Downloads/sonar-xquery-plugin-xquery3/target/generated-sources/antlr4/org/sonar/plugins/xquery/parser/XQueryParser.java:[224,9] method does not override or implement a method from a supertype
[ERROR] /Users/lcahlander/Downloads/sonar-xquery-plugin-xquery3/target/generated-sources/antlr4/org/sonar/plugins/xquery/parser/XQueryParser.java:[230,9] method does not override or implement a method from a supertype
[ERROR] /Users/lcahlander/Downloads/sonar-xquery-plugin-xquery3/target/generated-sources/antlr4/org/sonar/plugins/xquery/parser/XQueryParser.java:[233,9] method does not override or implement a method from a supertype
[ERROR] /Users/lcahlander/Downloads/sonar-xquery-plugin-xquery3/target/generated-sources/antlr4/org/sonar/plugins/xquery/parser/XQueryParser.java:[236,9] method does not override or implement a method from a supertype
[ERROR] /Users/lcahlander/Downloads/sonar-xquery-plugin-xquery3/target/generated-sources/antlr4/org/sonar/plugins/xquery/parser/XQueryParser.java:[239,9] method does not override or implement a method from a supertype
[ERROR] /Users/lcahlander/Downloads/sonar-xquery-plugin-xquery3/target/generated-sources/antlr4/org/sonar/plugins/xquery/parser/XQueryParser.java:[244,17] cannot find symbol
[ERROR]   symbol:   variable _interp
[ERROR]   location: class org.sonar.plugins.xquery.parser.XQueryParser
[ERROR] /Users/lcahlander/Downloads/sonar-xquery-plugin-xquery3/target/generated-sources/antlr4/org/sonar/plugins/xquery/parser/XQueryParser.java:[244,50] incompatible types: org.sonar.plugins.xquery.parser.XQueryParser cannot be converted to org.antlr.v4.runtime.Parser
.
.
.
